services:
  - type: web
    name: tg-bio-scrobbler
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m http.server $PORT & python runner.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: LASTFM_API_KEY
        sync: false
      - key: LASTFM_USERNAME
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.0
