services:
  - type: worker
    name: tg-bio-scrobbler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python runner.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: LASTFM_API_KEY
        sync: false
      - key: LASTFM_USERNAME
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: GUIDE_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.0
